(function(){
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[-–—/]/g,' ');
const synonyms={'cannot start':'task launch executive initiation','getting started':'task launch initiation','aphasia':'communication language','meltdown':'overload sensory regulation','sad':'depression mood','risk':'safety suicide crisis','biting':'behavior conflict','worry':'anxiety uncertainty','ocd':'ocd uncertainty exposure erp','iep':'iep school access','paraprofessional':'workforce frontline staff','case manager':'workforce frontline coordination','autistic':'autism autistic','adhd':'adhd attention executive'};
function matches(r,state){const query=norm(state.q).trim();const expanded=synonyms[query];const hay=norm([r.title,r.url,...Object.values(r.tags).flat()].join(' '));const queryOK=!query||query.split(/\s+/).every(t=>hay.includes(t))||(expanded&&expanded.split(' ').some(t=>hay.includes(t)));return !!queryOK&&Object.entries(state).every(([k,v])=>k==='q'||!v||(r.tags[k]||[]).includes(v));}
function search(resources,state){return resources.filter(r=>matches(r,state)).sort((a,b)=>b.priority-a.priority||a.title.localeCompare(b.title));}
function related(resource,resources){const keys=['diagnosis','function','task'];return resources.filter(r=>r.url!==resource.url).map(r=>({r,score:keys.reduce((n,k)=>n+(r.tags[k]||[]).filter(t=>(resource.tags[k]||[]).includes(t)).length,0)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score||b.r.priority-a.r.priority||a.r.title.localeCompare(b.r.title)).slice(0,3).map(x=>x.r);}
function decode(params,facets){const state={q:(params.get('q')||'').slice(0,160)};for(const [key,values] of Object.entries(facets)){const v=params.get(key)||'';state[key]=values.includes(v)?v:'';}return state;}
const routes={
 'What am I seeing?':{text:'Describe observable events, listen to the person, and check safety and access before assigning a label.',links:[['/resources/therapy/frontline-observation-coordination.html','Observation & coordination'],['/resources/training/workforce-learning-center.html','Practice neutral observation']]},
 'Understanding':{text:'Keep competing explanations open. Compare health, communication, skill demands, context, and learning history.',links:[['/resources/therapy/barrier-formulation-lab.html','Formulation lab'],['/resources/assessment/integrated-development-language-learning-casebook.html','Integrated casebook']]},
 'What should I do?':{text:'Agree goals and match supports to needs, evidence, access, competence, and supervision. Assessment decisions sit within the fuller guides.',links:[['/resources/therapy/treatment-plan-menu.html','Treatment-planning menu'],['/resources/therapy/family-pattern-support-experiment.html','Family support experiment']]},
 'What tool?':{text:'Choose a tool that enables understanding and participation. Adapt language and format; preserve the clinical purpose.',links:[['/resources/therapy/visual-reasoning-toolkit.html','Visual reasoning toolkit'],['/resources/therapy/communication-supports-toolkit.html','Communication supports']]},
 'What to watch next?':{text:'Review everyday function, distress, access, learning, support burden, adverse effects, and the person’s experience.',links:[['/resources/therapy/functional-progress-review.html','Functional progress review'],['/resources/school/school-support-implementation-log.html','School implementation log']]}
};
if(typeof module!=='undefined')module.exports={matches,search,related,decode,norm,routes};
if(typeof document==='undefined')return;
const data=globalThis.CPLFinderData;const by=id=>document.getElementById(id);const labels={diagnosis:'Diagnosis / collection',symptom:'Symptom / presentation',function:'Functional difficulty',intervention:'Intervention',stage:'Developmental coverage',role:'Audience / role',task:'Clinical task',step:'Pathway step'};
let state=decode(new URLSearchParams(location.search),data.facets),limit=24;const selects={};
for(const [key,values] of Object.entries(data.facets)){const wrap=document.createElement('div'),label=document.createElement('label'),select=document.createElement('select');label.htmlFor='facet-'+key;label.textContent=labels[key];select.id='facet-'+key;const all=document.createElement('option');all.value='';all.textContent='All';select.appendChild(all);values.forEach(v=>{const option=document.createElement('option');option.value=v;option.textContent=v;select.appendChild(option);});select.value=state[key];select.addEventListener('change',()=>{state[key]=select.value;limit=24;render();});wrap.append(label,select);by('facet-controls').appendChild(wrap);selects[key]=select;}
function link(url,title){const a=document.createElement('a');a.href=url;a.textContent=title;return a;}
function updateRoute(){const host=by('pathway-guide');host.replaceChildren();const route=routes[state.step];if(route){const heading=document.createElement('strong');heading.textContent=state.step;const p=document.createElement('p');p.textContent=route.text;const links=document.createElement('div');links.className='pathway-links';route.links.forEach(([url,title])=>links.appendChild(link(url,title)));host.append(heading,p,links);}else{const p=document.createElement('p');p.textContent='Search across all five clinical pathway steps. Original diagnosis guides preserve deeper clinical and educational reasoning.';host.appendChild(p);}document.querySelectorAll('[data-step]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.step===state.step)));}
function render(updateURL=true){by('finder-query').value=state.q;Object.keys(selects).forEach(k=>selects[k].value=state[k]);const found=search(data.resources,state);by('finder-results').replaceChildren();found.slice(0,limit).forEach(r=>{const card=document.createElement('article');card.className='finder-card';const heading=document.createElement('h3');heading.appendChild(link(r.url,r.title));const meta=document.createElement('small');meta.textContent=r.format+' · Current Colorful resource';const tags=document.createElement('div');tags.className='tag-list';[...new Set([...r.tags.diagnosis,...r.tags.function,...r.tags.role])].slice(0,5).forEach(t=>{const tag=document.createElement('span');tag.className='tag';tag.textContent=t;tags.appendChild(tag);});card.append(heading,meta,tags);const recommended=related(r,data.resources);if(recommended.length){const details=document.createElement('details'),summary=document.createElement('summary'),ul=document.createElement('ul');summary.textContent='Related resources';recommended.forEach(item=>{const li=document.createElement('li');li.appendChild(link(item.url,item.title));ul.appendChild(li);});details.append(summary,ul);card.appendChild(details);}by('finder-results').appendChild(card);});by('finder-status').textContent=found.length+' matching resources; showing '+Math.min(limit,found.length)+'. Discovery tags are not clinical approval.';by('finder-empty').hidden=found.length>0;by('finder-more').hidden=limit>=found.length;updateRoute();if(updateURL){const params=new URLSearchParams();for(const [k,v] of Object.entries(state))if(v)params.set(k,v);history.replaceState(null,'',location.pathname+(params.size?'?'+params.toString():'')+location.hash);}}
by('finder-query').addEventListener('input',()=>{state.q=by('finder-query').value.slice(0,160);limit=24;render();});by('finder-reset').addEventListener('click',()=>{state=decode(new URLSearchParams(),data.facets);limit=24;render();});by('finder-more').addEventListener('click',()=>{limit+=24;render();});document.querySelectorAll('[data-step]').forEach(b=>b.addEventListener('click',()=>{state.step=state.step===b.dataset.step?'':b.dataset.step;limit=24;render();}));addEventListener('popstate',()=>{state=decode(new URLSearchParams(location.search),data.facets);limit=24;render(false);});render(false);
})();
