"""Generate original, individually authored clinical topic resources in five-topic waves."""
import argparse,html,json,runpy
from pathlib import Path
R=Path(__file__).resolve().parents[1]; content=runpy.run_path(str(R/'scripts/expansion-topics.py')); E=html.escape
p=argparse.ArgumentParser();p.add_argument('--waves',type=int,default=1);a=p.parse_args();topics=content['TOPICS'][:a.waves*5];sources=content['SOURCES']
KINDS={'formulation':'Clinician formulation guide','case':'Interactive case practice','support-map':'Visual support map','client-workbook':'Client workbook','care-partner':'Care-partner guide','progress-review':'Progress review tool'}
def pairs(items):return ''.join(f'<h3>{E(t)}</h3><p>{E(v)}</p>' for t,v in items)
def fields(labels,prefix):return ''.join(f'<label for="{prefix}-{i}">{E(v)}</label><textarea id="{prefix}-{i}" autocomplete="off" spellcheck="true"></textarea>' for i,v in enumerate(labels))
def sources_html(t):
 return '<details><summary>Evidence, source access and review limits</summary><p>Principles below are linked to source families; the maps, case, prompts and monitoring plan are original CPL teaching aids. They have not been validated as measures or professionally approved. No proprietary test items or source worksheets are reproduced. Source review: 2026-10-10.</p><ul>'+''.join(f'<li><a href="{E(sources[s][1])}">{E(sources[s][0])}</a> — {E(sources[s][2])}. {E(sources[s][3])}.</li>' for s in t['sources'])+'</ul><p>'+E(t['limits'])+'</p></details>'
def page(title,body,t=None):
 return '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+E(title)+' | Clinical Practice Library</title><link rel="stylesheet" href="/resources/clinical-expansion.css"><link rel="stylesheet" href="/resources/clinical-topics/topic-tools.css"><script src="/resources/clinical-topics/topic-tools.js" defer></script></head><body><a class="skip" href="#content">Skip to content</a><header><a href="/">Library subject index</a><a href="/resources/clinical-topics/index.html">Clinical topic collections</a><a href="/resources/clinical-resource-finder.html">Search & filter</a><a href="/#diagnosis-guides">Original diagnosis guides</a></header><main id="content"><h1>'+E(title)+'</h1>'+body+(sources_html(t) if t else '')+'<footer>Clinical Practice Library · Sophia Korb Cohon, PhD · Original educational resources · <a href="/resources/qa-status.html">QA and qualified review needs</a></footer></main></body></html>\n'
ledger=[]
for t in topics:
 d=R/'resources/clinical-topics'/t['slug'];d.mkdir(exist_ok=True)
 download='<p><a href="/resources/downloads/topic-'+t['slug']+'.pdf">Download original support worksheet (PDF)</a> · Printable companion; not a separate counted resource.</p>'
 originals={'adult-adhd-task-starts':['adhd'],'adult-autism-load-recovery':['autism'],'panic-alarm-loop':['anxiety'],'social-anxiety-attention':['anxiety'],'ocd-mental-rituals':['anxiety'],'depression-activity-reward':['depression'],'learning-instruction-access':['dyslexia','dyscalculia','dysgraphia']}
 original_links='<p>Related original school-age diagnosis collections: '+', '.join('<a href="/guides/'+key+'.html">'+key.title()+' family guide</a> · <a href="/resources/school/clinical/'+key+'.html">clinical school guide</a>' for key in originals.get(t['slug'],[]))+'</p>' if t['slug'] in originals else ''
 nav='<nav class="topic-nav" aria-label="Topic resources">'+''.join(f'<a href="/resources/clinical-topics/{t["slug"]}/{k}.html">{E(v)}</a>' for k,v in KINDS.items())+'</nav>'
 context='<p class="eyebrow">'+E(t['age'])+' · Presentation → Understanding → Assessment → Intervention → Tools → Monitoring</p><p>'+E(t['presentation'])+'</p>'
 boundary='<aside class="note"><h2>Safety and scope</h2><p>'+E(t['safety'])+'</p><p>Staff and care partners can support communication, observe and coordinate within their authorized role. Diagnosis, treatment selection and specialized interventions require appropriate training and supervision. This page is not a crisis service.</p></aside>'
 instructions='<p class="no-print">Use fictional or appropriately de-identified notes. Entries stay in this open page; they are not saved or sent by this tool. Browser extensions or shared computers may still expose them. Clearing or leaving loses entries. Printing may include your notes.</p><div class="controls"><button type="button" data-print>Print worksheet</button><button type="button" data-clear>Clear entries</button></div>'
 map_modifiers={'panic-alarm-loop':'return-loop','ocd-mental-rituals':'loop-choice','aphasia-communication-access':'access-tracks','child-aggression-caregiver-coaching':'abc-tracks','sibling-conflict-safety-repair':'safety-gate','restrictive-eating-coordination':'parallel-assess','intellectual-disability-supported-choice':'access-tracks','health-anxiety-medical-plan':'loop-choice','body-dysmorphia-checking':'loop-choice','adult-autism-load-recovery':'context-budget','social-anxiety-attention':'attention-split','depression-activity-reward':'loop-choice','binge-eating-patterns':'loop-choice'}
 map_notes={'panic-alarm-loop':'Possible feedback loop: the short-term response can shape attention to the next sensation. This is a hypothesis to check, not a prediction or diagnosis.','ocd-mental-rituals':'The first four cards may repeat. The final card represents an agreed, supported alternative response rather than a guaranteed exit from distress.','aphasia-communication-access':'Consider message, response mode and access conditions together. Then verify the person\'s meaning and agree on a participation step; never infer capacity from speech alone.','child-aggression-caregiver-coaching':'Before, observed action and after are descriptive observations. Compare explanations before selecting a safer support and skill; one ABC event does not establish behavioral function.','sibling-conflict-safety-repair':'Safety and freedom to decline determine the route. Protective adult action is not contingent on agreeing to repair; voluntary repair is considered only after safety is established.','restrictive-eating-coordination':'Medical stability and psychological or sensory formulation need parallel attention. Do not wait for a completed behavioral explanation before urgent medical assessment; one team coordinates the plan.','intellectual-disability-supported-choice':'Real options, communication access and a response mode must be available together before checking meaning. Support choice without assuming agreement, capacity or inability from one answer.','health-anxiety-medical-plan':'The first four stages describe a possible repeating response pattern. The final two-part plan preserves appropriate medical evaluation while offering an agreed anxiety intervention; it does not dismiss new symptoms.','body-dysmorphia-checking':'The first four stages describe a possible checking-concealment loop. The last step is a collaboratively chosen treatment goal, not a demand to stop coping or an automatic diagnosis.','adult-autism-load-recovery':'Demands and available access interact; visible and hidden effort affect recovery needs. Evaluate a support experiment by participation and its cost, not by apparent compliance.','social-anxiety-attention':'Distinguish feared evaluation from attention and access needs. Self-monitoring and contact with others compete for attention; review whether support helps without assuming every accommodation is avoidance.','depression-activity-reward':'Rest can restore capacity and withdrawal can protect against overload. Where an avoidance/reward loop seems plausible, the final card is a voluntary, supported alternative, not a command to push through symptoms.','binge-eating-patterns':'These first four stages may recur but do not establish a cause, diagnosis or personal failure. Care should prioritize assessment, privacy and a feasible plan; avoid prescribing compensatory restriction.'}
 mapmodifier=map_modifiers.get(t['slug'],'two-track' if t['slug']=='learning-instruction-access' else '')
 mapclass='clinical-map'+(' '+mapmodifier if mapmodifier else '')
 diagram='<ol class="'+mapclass+'" aria-label="'+E(t['title'])+' pathway">'+''.join(f'<li><strong>{E(n)}</strong><span>{E(v)}</span></li>' for n,v in t['diagram'])+'</ol>'+('<p>Instruction and access run in parallel. Review skill learning and knowledge demonstration separately.</p>' if t['slug']=='learning-instruction-access' else '')
 if t['slug'] in map_notes: diagram+='<p class="map-legend">'+E(map_notes[t['slug']])+'</p>'
 if t['slug']=='sibling-conflict-safety-repair': diagram+="<div class=\"safety-fork\" role=\"group\" aria-label=\"Two safety-dependent response routes\"><section class=\"protect-route\"><h3>Safety or free choice is absent</h3><p>Protect the child, assess immediate risks and follow appropriate safeguarding pathways. Do not require joint mediation, apology or repair.</p></section><section class=\"repair-route\"><h3>Both children are safe and may freely decline</h3><p>Adults can coach concrete skills and offer a voluntary, supported repair option. A child may refuse without penalty.</p></section></div>"
 for kind,label in KINDS.items():
  title=t['title']+' — '+label
  if kind=='formulation':
   body=context+'<h2>Understanding the pattern</h2><p>'+E(t['understanding'])+'</p><h2>Keep competing explanations open</h2>'+pairs(t['hypotheses'])+'<h2>'+('Assessment planning questions for the interviewer/team' if t['slug']=='intellectual-disability-supported-choice' else 'Ask the person or caregiver')+'</h2><ul>'+''.join('<li>'+E(q)+'</li>' for q in t['questions'])+'</ul><details open><summary>Instructions for the interviewer</summary><p>Ask one question at a time, use the person\'s preferred language/response mode, and distinguish direct observations, attributed reports and hypotheses. Do not read these instructions as interview questions. Ask permission before collateral contact and explain confidentiality limits. Record contradictions and missing information.</p></details><h2>Intervention selection and coordination</h2>'+pairs(t['actions'])
  elif kind=='case':
   body='<p class="eyebrow">Supervised reasoning practice · '+E(t['age'])+'</p><p>'+E(t['case'])+'</p><fieldset class="case-options"><legend>What is the most useful next step, and why?</legend>'+''.join(f'<button type="button" data-feedback="{E(feedback,quote=True)}">{E(choice)}</button>' for choice,feedback in (t['choices'][topics.index(t)%3:]+t['choices'][:topics.index(t)%3]))+'</fieldset><div class="case-feedback note" role="status" aria-live="polite"><p>Choose an option to review the reasoning. This does not score clinical competence.</p></div><noscript><h2>Worked feedback</h2>'+pairs(t['choices'])+'</noscript><details><summary>Worked formulation and supervision prompts</summary><p>'+E(t['understanding'])+'</p><h3>What still needs assessment?</h3><ul>'+''.join('<li>'+E(q)+'</li>' for q in t['questions'])+'</ul><p>Explain which information could change your plan, which tasks your role permits, and who owns the next handoff. Ask a supervisor to review the reasoning and communication, rather than treating the preferred option as a universal answer.</p></details>'+instructions+fields(['What information would change my next step?','What can I do within my role, and who must assess further?','How will I confirm the handoff and review the person\'s response?'],'case')
  elif kind=='support-map':
   body=context+'<h2>How the parts relate</h2>'+diagram+'<p>This map organizes a conversation; it does not establish causation or calculate risk. Follow the sequence for one event, then return to context and competing explanations. The arrows show a proposed relationship to examine, not proof.</p>'+instructions+fields(t['fields'],'map')+'<details><summary>Clinician layer: what the map could miss</summary>'+pairs(t['hypotheses'])+'<p>'+E(t['understanding'])+'</p></details><details><summary>Worked example</summary><p>'+E(t['case'])+'</p><p>'+E(t['choices'][1][1])+'</p></details>'
  elif kind=='client-workbook':
   body='<p class="eyebrow">Plain-language participation aid · '+E(t['age'])+'</p><p>You can write, draw, point, dictate or ask someone you trust to help. You can skip a question. This worksheet helps you describe your experience and preferences; it does not diagnose you or decide treatment.</p>'+pairs(t['client'])+instructions+fields([v[0]+' — what would I like my team to know?' for v in t['client']],'client')+'<h2>Before you finish</h2><p>Choose one item to discuss with your care team. Ask what choices are available, what the proposed support is meant to help, and when you will review it. Tell the team if a support feels unsafe, inaccessible or unhelpful.</p>'
  elif kind=='care-partner':
   body='<p class="eyebrow">Caregiver, family or chosen supporter · '+E(t['age'])+'</p><p>The person decides whom they want involved whenever possible. Ask about privacy, preferred communication and practical help before using this guide. Your role is support and a clear handoff, not diagnosis or independent specialist treatment.</p>'+pairs(t['care'])+'<h2>A specific support agreement</h2>'+instructions+fields(['What help has the person agreed to, and what do they want kept private?','What I observed; what the person reported; what remains uncertain','One practical action, who will do it, and when','Who receives a concern; how will I confirm follow-up?'],'care')+'<details><summary>Why the clinical formulation matters</summary><p>'+E(t['understanding'])+'</p><p>Discuss the formulation with the treating clinician when invited; do not use it to assign motives, override consent or change medication.</p></details>'
  else:
   body='<p class="eyebrow">Collaborative functional review · '+E(t['age'])+'</p><p>Choose one or two meaningful outcomes with the person. Agree the observation period, context and support before baseline. Compare like situations where possible, and retain uncertainty when conditions change. These indicators are individualized observations, not a validated scale or diagnostic score.</p><div class="table"><table><caption>What to track and why</caption><thead><tr><th scope="col">Indicator</th><th scope="col">Interpretation and limits</th></tr></thead><tbody>'+''.join(f'<tr><th scope="row">{E(n)}</th><td>{E(v)}</td></tr>' for n,v in t['metrics'])+'</tbody></table></div>'+instructions+fields(['Chosen goal and what meaningful improvement would look like','Baseline: dates, context, participation and support needed','Follow-up: dates, same/different context and observed change','Person\'s view: helpful, burdensome, unwanted or harmful?','Decision with the team: continue, adapt, assess further; owner and review date'],'review')+'<h2>Interpret change carefully</h2><p>Ask whether access, health, demands, relationships or support changed. Fewer visible symptoms can reflect avoidance, suppression or fewer opportunities. More participation can matter even while distress remains. Missing data is missing data, not evidence of improvement.</p><details><summary>Options to discuss, not automatic rules</summary>'+pairs(t['actions'])+'</details><p>Urgent deterioration bypasses the routine review date. No percentage change on this worksheet authorizes a diagnosis, medication adjustment or discharge.</p>'
  (d/(kind+'.html')).write_text(page(title,nav+original_links+body+download+boundary,t))
  ledger.append({'path':f'resources/clinical-topics/{t["slug"]}/{kind}.html','topic':t['slug'],'title':title,'type':kind,'audience':t['age'],'sources':t['sources'],'wave':topics.index(t)//5+1,'reviewDate':'2026-10-10','qualifiedClinicalReview':'pending','browserQA':'unavailable','countedResource':True})
 topic_body=original_links+context+'<p>'+E(t['understanding'])+'</p>'+nav+'<h2>Practical pathway</h2>'+diagram+boundary
 (d/'index.html').write_text(page(t['title'],topic_body,t))
 hub='<p>Original layered topic sets connect formulation, practical choices and functional review. Start with a topic, then choose the resource for your role. They complement the retained diagnosis guides; they do not replace assessment or specialized treatment.</p><p><a href="/#diagnosis-guides">Original diagnosis collections</a> · <a href="/resources/therapy/authoritative-resource-directory.html">External authoritative directory</a></p><div class="table"><table><caption>Browse clinical topics and tools</caption><thead><tr><th scope="col">Topic</th><th scope="col">Resources</th></tr></thead><tbody>'+''.join('<tr><th scope="row"><a href="/resources/clinical-topics/'+x['slug']+'/index.html">'+E(x['title'])+'</a></th><td>'+''.join('<a href="/resources/clinical-topics/'+x['slug']+'/'+k+'.html">'+E(v)+'</a> · ' for k,v in KINDS.items())+'</td></tr>' for x in topics)+'</tbody></table></div><p>Review date: 2026-10-10. Qualified clinical review remains pending. These original tools are unvalidated teaching and planning aids. Source access limitations are documented within each topic.</p>'
(R/'resources/clinical-topics/index.html').write_text(page('Clinical topic collections',hub))
(R/'data/topic-expansion-ledger.json').write_text(json.dumps({'target':150,'completedMeaningfulResources':len(ledger),'countPolicy':'Six distinct purposes per topic. Collection pages, PDFs, shared assets and cosmetic changes excluded. Count does not certify clinical quality.','resources':ledger},indent=2)+'\n')
(R/'data/topic-evidence-registry.json').write_text(json.dumps({'reviewDate':'2026-10-10','qualifiedReview':'pending','sources':{s:dict(zip(['title','url','evidenceType','access'],sources[s])) for s in sorted({s for t in topics for s in t['sources']})},'topicCrosswalk':[{k:t[k] for k in ['slug','title','age','sources','limits']} for t in topics]},indent=2)+'\n')
# Keep generator output byte-for-byte consistent with the published static top navigation.
site_nav = runpy.run_path(str(R/'scripts/site-navigation.py'))
site_nav['apply_to_files'](R, scope='resources/clinical-topics/')
print(len(topics),'topics;',len(ledger),'distinct resource pages; collection pages excluded')
